In [1]:
import pandas as pd

In [2]:
from pandas import Series,DataFrame

In [3]:
obj = pd.Series([4,7,-3,5])

In [4]:
obj

0    4
1    7
2   -3
3    5
dtype: int64

In [5]:
obj.values

array([ 4,  7, -3,  5], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,-7,5,3],index=['d','b','a','c'])

In [8]:
obj2

d    4
b   -7
a    5
c    3
dtype: int64

In [9]:
obj2['a']

5

In [10]:
obj2['b'] = 6

In [11]:
obj2

d    4
b    6
a    5
c    3
dtype: int64

In [12]:
obj2[obj2 > 0]

d    4
b    6
a    5
c    3
dtype: int64

In [13]:
obj2 * 2

d     8
b    12
a    10
c     6
dtype: int64

In [14]:
import numpy as np

In [15]:
np.exp(obj2)

d     54.598150
b    403.428793
a    148.413159
c     20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [18]:
obj3 = pd.Series(sdata)

In [19]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
states = ['Califonia','Ohio','Oregon','Texas']

In [21]:
obj4 = pd.Series(sdata,index=states)

In [22]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [23]:
pd.isnull(obj4)

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [24]:
pd.notnull(obj4)

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [25]:
obj4.isnull()

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [26]:
obj3 + obj4

Califonia         NaN
Ohio          70000.0
Oregon        32000.0
Texas        142000.0
Utah              NaN
dtype: float64

In [27]:
obj4.name = 'population'

In [28]:
obj4.index.name = 'state'

In [29]:
obj4

state
Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64

In [30]:
obj

0    4
1    7
2   -3
3    5
dtype: int64

In [31]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [32]:
obj

Bob      4
Steve    7
Jeff    -3
Ryan     5
dtype: int64

In [33]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
    'year':[2000,2001,2002,2001,2002,2003],
    'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [34]:
frame = pd.DataFrame(data)

In [35]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [37]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [38]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
    index=['one','two','three','four','five','six'])

In [39]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [42]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [43]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [44]:
frame2['debt'] = 16.5

In [45]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [46]:
frame2['debt'] = np.arange(6)

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [48]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [49]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [50]:
frame2['debt'] = val

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [52]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [53]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [54]:
pop = {'Nevada':{2001:2.4,2002:2.9},
    'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [55]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [56]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [57]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [58]:
pdata = {'Ohio':frame3['Ohio'][:-1],
    'Nevada':frame3['Nevada'][:2]}

In [59]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [60]:
frame3.index.name = 'year';frame3.columns.name = 'state'

In [61]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [62]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [63]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [64]:
obj = pd.Series(range(3),index=['a','b','c'])

In [65]:
index = obj.index

In [66]:
index

Index(['a', 'b', 'c'], dtype='object')

In [67]:
index[1:]

Index(['b', 'c'], dtype='object')

In [68]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [69]:
labels = pd.Index(np.arange(3))

In [70]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [71]:
obj2 = pd.Series([1.5,-2.5,9],index=labels)
obj2

0    1.5
1   -2.5
2    9.0
dtype: float64

In [72]:
obj2.index is labels

True

In [73]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [74]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [75]:
'Ohio' in frame3.columns

True

In [76]:
2003 in frame3.index

False

In [77]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [78]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [79]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [80]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [81]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [82]:
obj3 = pd.Series(['bule','purple','yellow'],index=[0,2,4])
obj3

0      bule
2    purple
4    yellow
dtype: object

In [83]:
obj3.reindex(range(6),method='ffill')

0      bule
1      bule
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [84]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
    index=['a','c','d'],
    columns=['Ohio','Texas','California'])

In [85]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [86]:
frame2 = frame.reindex(['a','b','c','d'])

In [87]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [88]:
states = ['Texas','Utah','California']

In [89]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [90]:
frame.loc[['a','b','c','d'],states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [91]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [92]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [93]:
new_obj = obj.drop('c')

In [94]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [95]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
    index=['Ohio','Colorado','Utah','New York'],
    columns=['one','two','three','four'])

In [96]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [97]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data.drop('two',axis='columns')

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [99]:
data.drop(['one','three'],axis='columns')

two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

In [100]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [101]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [102]:
obj.drop('c',inplace=True)

In [103]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [104]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])

In [105]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [106]:
obj['b']

1.0

In [107]:
obj[1]

1.0

In [108]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [109]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [110]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [111]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [112]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [113]:
obj['b':'c'] = 5

In [114]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [115]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
    index=['Ohio','Colorado','Utah','New York'],
    columns=['one','two','three','four'])

In [116]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [117]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [118]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [119]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [120]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [121]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [122]:
data[data < 5] = 0

In [123]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [124]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [125]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [126]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [128]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [129]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [130]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [131]:
data.iloc[:][data.three > 5]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [132]:
ser = pd.Series(np.aragne(3.))

AttributeError: module 'numpy' has no attribute 'aragne'

In [133]:
import pandas as pd
import numpy as np

In [134]:
ser = pd.Series(np.arange(3.))

In [135]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [136]:
ser[-1]

KeyError: -1

In [137]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [138]:
ser2[-1]

2.0

In [139]:
ser[:1]

0    0.0
dtype: float64

In [140]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [141]:
ser.iloc[:1]

0    0.0
dtype: float64

In [142]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
    index=['a','c','e','f','g'])

In [143]:
s1
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [144]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [145]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [146]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=
    list('bcd'),index=['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=
    list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [147]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [148]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [149]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [150]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})

In [151]:
df1

A
0  1
1  2

In [152]:
df2

B
0  3
1  4

In [153]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [154]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
    columns=list('abcd'))

In [155]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
    columns=list('abcde'))

In [156]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [157]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [158]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [159]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [160]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [161]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [163]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [164]:
arr = np.arange(12.).reshape((3,4))

In [165]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [166]:
arr[0]

array([0., 1., 2., 3.])

In [167]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [168]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [169]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
    columns=list('bcd'),index=['Utah','Ohio','Texas','Orengon'])

In [170]:
frame

b     c     d
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Orengon  9.0  10.0  11.0

In [171]:
series = frame.iloc[0]
series

b    0.0
c    1.0
d    2.0
Name: Utah, dtype: float64

In [172]:
frame - series

b    c    d
Utah     0.0  0.0  0.0
Ohio     3.0  3.0  3.0
Texas    6.0  6.0  6.0
Orengon  9.0  9.0  9.0

In [173]:
series2 = pd.Series(range(3),index=['b','e','f'])

In [174]:
frame + series2

b   c   d   e   f
Utah     0.0 NaN NaN NaN NaN
Ohio     3.0 NaN NaN NaN NaN
Texas    6.0 NaN NaN NaN NaN
Orengon  9.0 NaN NaN NaN NaN

In [175]:
serise3 = frame['d']

In [176]:
frame

b     c     d
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Orengon  9.0  10.0  11.0

In [177]:
serise3

Utah        2.0
Ohio        5.0
Texas       8.0
Orengon    11.0
Name: d, dtype: float64

In [178]:
series3 = serise3

In [179]:
series2

b    0
e    1
f    2
dtype: int64

In [180]:
frame

b     c     d
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Orengon  9.0  10.0  11.0

In [181]:
frame

b     c     d
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Orengon  9.0  10.0  11.0

In [182]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
    columns=list('bde'),index=['Utah','Ohio','Texas','Orengon'])

In [183]:
frame + series2

b   d     e   f
Utah     0.0 NaN   3.0 NaN
Ohio     3.0 NaN   6.0 NaN
Texas    6.0 NaN   9.0 NaN
Orengon  9.0 NaN  12.0 NaN

In [184]:
series3 = frame['d']

In [185]:
frame

b     d     e
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Orengon  9.0  10.0  11.0

In [186]:
series3

Utah        1.0
Ohio        4.0
Texas       7.0
Orengon    10.0
Name: d, dtype: float64

In [187]:
frame.sub(series3,axis='index')

b    d    e
Utah    -1.0  0.0  1.0
Ohio    -1.0  0.0  1.0
Texas   -1.0  0.0  1.0
Orengon -1.0  0.0  1.0

In [188]:
frame.sub(series3)

Ohio  Orengon  Texas  Utah   b   d   e
Utah      NaN      NaN    NaN   NaN NaN NaN NaN
Ohio      NaN      NaN    NaN   NaN NaN NaN NaN
Texas     NaN      NaN    NaN   NaN NaN NaN NaN
Orengon   NaN      NaN    NaN   NaN NaN NaN NaN

In [189]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
    index=['Utah','Ohio','Texas','Oregon'])

In [190]:
frame

b         d         e
Utah   -0.743390  0.232339  0.723915
Ohio    0.118872  1.661590  1.634486
Texas  -0.076462 -1.271524  0.282462
Oregon -0.841274  0.514555 -0.933255

In [191]:
np.abs(frame)

b         d         e
Utah    0.743390  0.232339  0.723915
Ohio    0.118872  1.661590  1.634486
Texas   0.076462  1.271524  0.282462
Oregon  0.841274  0.514555  0.933255

In [192]:
f = lambda x:x.max() - x.min()

In [193]:
frame.apply(f)

b    0.960147
d    2.933114
e    2.567741
dtype: float64

In [194]:
frame.apply(f,axis='index')

b    0.960147
d    2.933114
e    2.567741
dtype: float64

In [195]:
frame.apply(f,axis='columns')

Utah      1.467305
Ohio      1.542718
Texas     1.553985
Oregon    1.447810
dtype: float64

In [202]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [200]:
frame.apply(f())

TypeError: f() missing 1 required positional argument: 'x'

In [203]:
frame.apply(f)

b         d         e
min -0.841274 -1.271524 -0.933255
max  0.118872  1.661590  1.634486

In [204]:
format = lambda x: '%.2f' % x

In [205]:
frame.applymap(format)

b      d      e
Utah    -0.74   0.23   0.72
Ohio     0.12   1.66   1.63
Texas   -0.08  -1.27   0.28
Oregon  -0.84   0.51  -0.93

In [206]:
frame['e'].map(format)

Utah       0.72
Ohio       1.63
Texas      0.28
Oregon    -0.93
Name: e, dtype: object

In [207]:
obj = pd.Series(range(4),index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [209]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [210]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
    index=['three','one'],columns=['d','a','b','c'])

In [211]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [212]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [213]:
obj = pd.Series([4,7,-3,2])

In [214]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [215]:
obj.sort_values(ascending=False)

1    7
0    4
3    2
2   -3
dtype: int64

In [216]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [217]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [218]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [219]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [220]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [221]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [222]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [223]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [224]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [225]:
obj.rank(ascending=False,method='first')

0    1.0
1    7.0
2    2.0
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [226]:
frame = pd.DataFrame({'d':[4.3,7,-3,2],'a':[0,1,0,1],
    'c':[-2,5,8,-2.5]})

In [227]:
frame

d  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [228]:
frame.rank(axis='columns')

d    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [229]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
    'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [230]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [231]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [232]:
obj.index.is_unique

False

In [233]:
obj['a']

a    0
a    1
dtype: int64

In [234]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
df

0         1         2
a  1.216362  0.617746  0.062343
a  0.579579 -1.142926  0.920796
b  0.938770  1.431539 -0.605673
b  1.400727 -0.428475  2.527621

In [235]:
df.loc['b']

0         1         2
b  0.938770  1.431539 -0.605673
b  1.400727 -0.428475  2.527621

In [236]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],
    [0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [237]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [238]:
df.sum(axis=0)

one    9.25
two   -5.80
dtype: float64

In [239]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [240]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [241]:
df.idxmax()

one    b
two    d
dtype: object

In [242]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [243]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [244]:
obj = pd.Series(['a','a','b','c'] * 4)

In [245]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [246]:
import pandas_datareader.data as web

ModuleNotFoundError: No module named 'pandas_datareader'

In [247]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

In [248]:
uniques = obj.unique()

In [249]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [250]:
uniques.sort()

In [251]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [252]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [253]:
pd.value_counts(obj.values,sort=False)

d    1
b    2
a    3
c    3
dtype: int64

In [254]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [255]:
mask = obj.isin(['b','c'])

In [256]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [257]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [258]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [259]:
unique_vals = pd.Series(['c','b','a'])

In [260]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [261]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4],
    'Qu2':[2,3,1,2,3],
    'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [263]:
result = data.apply(pd.value_counts).fillna(0)

In [264]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0